---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/hg9a3205/cursoseloha.online/
    - /bin/mkdir -p $DEPLOYPATH/server
    - /bin/mkdir -p $DEPLOYPATH/client
    - /bin/cp -R server/dist $DEPLOYPATH/server/
    - /bin/cp server/package.json $DEPLOYPATH/server/
    - /bin/cp -R client/dist $DEPLOYPATH/client/
    - echo "Deploy de producao concluido com sucesso."
